import { Inter } from "next/font/google";
import "./globals.css";
// import { React } from "react";
import { ChakraProvider } from "@chakra-ui/provider";
import { Providers } from "./providers";
import Sidebar from "./Components/Sidebar";
import React from "react";
import { usePathname, useRouter } from "next/navigation";
import StoreProvider from "./StoreProvider";
// import { useAppSelector } from "@/lib/hooks";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alumni Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${inter.className} h-full `}>
        <Providers>
          <StoreProvider>
            <Sidebar>
              {children}
            </Sidebar>
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
